name: CI SpringBoot Angular MySQL

on:
  push:
    branches: [ "main" ]

jobs:
  build_push_test:
    runs-on: ubuntu-latest

    steps:
      # 1️ Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️ Setup Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3️ Build Spring Boot (création du .jar)
      - name: Build Spring Boot project
        run: |
          cd springboot/app
          mvn clean package -DskipTests

      # 4️ Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 5️ Login DockerHub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 6️ Build & Push Spring Boot image
      - name: Build & push Spring Boot image
        uses: docker/build-push-action@v6
        with:
          context: ./springboot/app
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/springboot-app:latest

      # 7️ Build & Push Angular image
      - name: Build & push Angular image
        uses: docker/build-push-action@v6
        with:
          context: ./angular-app
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/angular-app:latest

      # 8️ Start application
      - name: Start application with Docker Compose
        run: docker compose up -d

      - name: Show containers
        run: docker compose ps

      - name: Logs (debug)
        if: always()
        run: docker compose logs --no-color

      - name: Stop containers
        if: always()
        run: docker compose down